"""How often a game lands on a number, given the number it is priced at.

Football results are lumpy -- 8.9% of college games end on a 3-point margin, NFL
games 15.1% -- which is why half a point can be worth more than any rating edge
measured in this repo. But the lump is only reachable where the market has put
the line: given a home team laying 10, the chance of a 3-point home win is
nothing like the unconditional 8.9%. So every question here is asked
*conditionally* -- the sample is drawn from historical games priced near the
same number and recentred on it.

Counting that sample alone is not enough. A few hundred games leave 2-3% of
noise on every integer, which is the same size as the thing being measured, and
at long numbers it invents crossings worth "7%" that are two extra games. So the
counted distribution is shrunk toward a fitted shape: a normal with the sample's
own mean and spread, multiplied by how lumpy each number is over the *whole*
sample (``key_factors``). The lumps survive because they are measured across
thousands of games; the noise between them does not.

Tables are generated by ``scripts/lineshop/fit_distribution.py`` -- NFL from the
nflverse game file (1999+), CFB from CFBD's ``/lines`` median of real
sportsbooks (2014+).
"""

from __future__ import annotations

import json
import math
import statistics
from dataclasses import dataclass
from functools import cache, lru_cache
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"
SPORTS = ("cfb", "nfl")
MARGIN, TOTAL = "margin", "total"

# Widen the band of comparable lines until the sample is worth counting, then
# stop: beyond a few points the games are no longer priced like this one.
MIN_SAMPLE = 400
TOL_STEPS = (0.5, 1.0, 1.5, 2.0, 3.0)
# Games needed before the counted distribution is trusted over the fitted shape.
# At n=400 the count carries a third of the weight, at n=2000 five sixths.
SHRINK_K = 800.0
SUPPORT_SIGMAS = 5.0


@dataclass(frozen=True)
class Estimate:
    """A probability and the sample it was counted from."""

    p: float
    n: int
    tolerance: float

    @property
    def thin(self) -> bool:
        return self.n < MIN_SAMPLE


@dataclass(frozen=True)
class History:
    sport: str
    source: str
    counts: dict[str, dict[float, dict[float, int]]]  # market -> line -> result -> count
    key_factors: dict[str, dict[float, float]]  # market -> |number| -> lumpiness

    def games(self, market: str) -> int:
        return sum(sum(r.values()) for r in self.counts.get(market, {}).values())


@cache
def load(sport: str) -> History:
    payload = json.loads((DATA_DIR / f"{sport}_history.json").read_text())
    return History(
        sport=payload["sport"],
        source=payload["source"],
        counts={
            market: {
                float(line): {float(result): int(n) for result, n in results.items()}
                for line, results in lines.items()
            }
            for market, lines in payload["counts"].items()
        },
        key_factors={
            market: {float(value): float(f) for value, f in factors.items()}
            for market, factors in payload.get("key_factors", {}).items()
        },
    )


def _raw_sample(sport: str, market: str, line: float) -> tuple[dict[float, int], float]:
    """Historical results recentred on ``line``, and the tolerance used.

    A game priced at -9.5 informs a -10 game once its result is shifted by the
    difference. The shift is rounded so scores stay on the integers they landed
    on -- the whole point of this module is that 3 is not 3.5.
    """
    table = load(sport).counts.get(market, {})
    out: dict[float, int] = {}
    for tol in TOL_STEPS:
        out = {}
        total = 0
        for hist_line, results in table.items():
            if abs(hist_line - line) > tol:
                continue
            shift = math.floor(line - hist_line + 0.5)
            for result, n in results.items():
                out[result + shift] = out.get(result + shift, 0) + n
                total += n
        if total >= MIN_SAMPLE:
            return out, tol
    return out, TOL_STEPS[-1]


def _normal_mass(value: float, mean: float, sd: float) -> float:
    """P(result == value) for a normal rounded to the nearest integer."""
    hi = 0.5 * (1.0 + math.erf((value + 0.5 - mean) / (sd * math.sqrt(2.0))))
    lo = 0.5 * (1.0 + math.erf((value - 0.5 - mean) / (sd * math.sqrt(2.0))))
    return max(hi - lo, 0.0)


@lru_cache(maxsize=4096)
def pmf(sport: str, market: str, line: float) -> tuple[dict[float, float], int, float]:
    """The blended distribution of results for a game priced at ``line``."""
    counts, tol = _raw_sample(sport, market, line)
    n = sum(counts.values())
    if not n:
        return {}, 0, tol
    values = [v for v, c in counts.items() for _ in range(c)]
    mean = statistics.fmean(values)
    sd = statistics.pstdev(values) or 1.0
    factors = load(sport).key_factors.get(market, {})
    lo = math.floor(mean - SUPPORT_SIGMAS * sd)
    hi = math.ceil(mean + SUPPORT_SIGMAS * sd)
    support = sorted(set(range(lo, hi + 1)) | {int(v) for v in counts})
    shape = {
        float(v): _normal_mass(v, mean, sd)
        * factors.get(abs(v) if market == MARGIN else float(v), 1.0)
        for v in support
    }
    scale = sum(shape.values()) or 1.0
    weight = n / (n + SHRINK_K)
    blended = {
        v: weight * (counts.get(v, 0) / n) + (1.0 - weight) * mass / scale
        for v, mass in shape.items()
    }
    return blended, n, tol


def _estimate(sport: str, market: str, line: float, keep) -> Estimate:
    dist, n, tol = pmf(sport, market, line)
    if not n:
        return Estimate(0.0, 0, tol)
    return Estimate(sum(p for v, p in dist.items() if keep(v)), n, tol)


def p_between(sport: str, market: str, line: float, lo: float, hi: float) -> Estimate:
    """P(lo < result < hi) -- strict both ends, so a result sitting exactly on
    either number is a push rather than a hit."""
    return _estimate(sport, market, line, lambda v: lo < v < hi)


def p_at(sport: str, market: str, line: float, value: float) -> Estimate:
    return _estimate(sport, market, line, lambda v: v == value)


def p_above(sport: str, market: str, line: float, value: float) -> Estimate:
    return _estimate(sport, market, line, lambda v: v > value)
